name: Matrix Practice Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  matrix-test-job:
    # Используем переменную из матрицы для выбора ОС сервера!
    runs-on: ${{ matrix.os }}

    strategy:
      # Матрица — сердце этой джобы
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.11", "3.12"]

    steps:
      # Скачиваем код (базовый шаг)
      - name: Check out code
        uses: actions/checkout@v4

      # Специальный готовый Action для настройки Python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Подставляем версию динамически из матрицы
          python-version: ${{ matrix.python-version }}

      # Проверяем, что запустилось именно то, что мы просили
      - name: Verify Environment
        run: |
          echo "Текущая операционная система: ${{ matrix.os }}"
          python --version
